### ISSUE TITLE
Статусы текущего API

### ISSUE THREAD

**Issue by raywave** [m4l3vich/gosuslugi-cert-checker#1]
Исходя из анализов исходников сайта, сами запросы не отлавливал.

# TEMPORARY_CERT

> `OK` - Действителен
> `CANCELED` - Аннулирован
> `EXPIRED` - Истек
> `404` - Не найден
> Any Other - Не действителен

# VACCINE_CERT

> `1` - Действителен
> `404` - Не найден
> Any Other - Не действителен

# COVID_TEST

> `404` - not found
> `0` - Не дейсвителен
> `3` - Истек
> `Отрицательный` - отрицательный (может быть в любом кейсе)
> `Положительный` / _Any Other (в этом не уверен)_  - положительный (может быть в любом кейсе)

# ILLNESS_FACT

> `1` - переболел
> `3` - истек
> `404` - не найден
> Any Other - не действителен

**Comment by m4l3vich** [comment]
Имплементировал статусы в модуль с упрощением - вместо сотни статусов на выходе красивый boolean.
