### ISSUE TITLE
Актуальные запросы к API (февраль 2022)

### ISSUE THREAD

**Issue by Zerpico** [m4l3vich/gosuslugi-cert-checker#3]
На текущий момент 2-я версия вообще не работает. А большинство старых кодов ведут на устаревшие ссылки. С портала госуслуг в личном кабинете сгенерировали новые версии кодов с обновленными ссылками. 
Эмпирическим путём выявил такие варианты:

### version 1:

  URL: ```https://www.gosuslugi.ru/vaccine/cert/verify/{{uuid}}```
  API:   ```https://www.gosuslugi.ru/api/vaccine/v1/cert/verify/{{uuid}}```

 
### version 3:

  **Вариант 1**

    URL: ```https://www.gosuslugi.ru/covid-cert/status/{{uuid}}```
    API:   ```https://www.gosuslugi.ru/api/covid-cert-checker/v3/cert/status/{{uuid}}```

  **Вариант 2**

    URL: ```https://www.gosuslugi.ru/covid-cert/status/{{uuid}}?lang=ru```
    API:   ```https://www.gosuslugi.ru/api/covid-cert-checker/v3/cert/status/{{uuid}}?lang=ru```
 
 
### version 4:

  URL: ```https://www.gosuslugi.ru/covid-cert/verify/{{unrz}}?lang=ru&ck={{hash}}```
  API:   ```https://www.gosuslugi.ru/api/covid-cert/v4/cert/check/{{unrz}}?lang=ru&ck={{hash}}```

**Comment by Zerpico** [comment]
Json формат ответа кстати тоже имеет теперь 3 варианта

**Comment by m4l3vich** [comment]
Привет! Есть тестовые ссылки на сертификаты 4-й версии? Можешь скинуть куда-нибудь в лс?

**Comment by m4l3vich** [comment]
Однако, думаю, стоит отметить в документации, что 2-я версия теперь не работает.

**Comment by m4l3vich** [comment]
Посмотрел свои QR-коды и выяснил, что ответ API версии 4 полностью идентичен версии 2, изменилась только ссылка.

Как я понимаю всё это:
- Сертификаты вакцинации с ноября 2021 используют ссылки 3 версии, а ПЦР-тесты в это время (почему-то) использовали 2 версию;
- В конце января всплыла БД с данными сертификатов, формат которых соответствует ответам API 2 версии;
- Госуслуги отрубили сертификаты вакцинации 2 версии, потому что формат уже устаревший, и поддерживался только из-за того, что были старые QR-коды со старыми ссылками (сейчас в Госуслугах генерируется v3);
- Для работы QR-кодов ПЦР-тестов по-быстрому была скрафчена версия 4, которая поддерживает только ПЦР-тесты.

В ближайшее время обновлю модуль :)
